"""Vitals — Adw.Application subclass owning the in-process health core."""

from __future__ import annotations

import logging

from gi.repository import Adw, Gio, GLib, Gtk

from vitals.const import APP_ID, APP_NAME, VERSION
from vitals.core import migrate, resources
from vitals.core.catalog import Catalog
from vitals.core.events import RecordBus
from vitals.core.store import Store
from vitals.ingest import Recorder
from vitals.window import VitalsWindow

log = logging.getLogger(__name__)


class VitalsApplication(Adw.Application):
    def __init__(self):
        super().__init__(application_id=APP_ID,
                         flags=Gio.ApplicationFlags.DEFAULT_FLAGS)
        self.settings = Gio.Settings.new(APP_ID)
        self.store: Store | None = None
        self.catalog: Catalog | None = None
        self.record_bus = RecordBus()
        self.recorder: Recorder | None = None
        self._adoption: dict | None = None

        # Registered so --help lists it and Gio accepts it; the actual
        # level is read from sys.argv by configure_logging().
        self.add_main_option(
            "debug", ord("d"), GLib.OptionFlags.NONE, GLib.OptionArg.NONE,
            "Enable debug logging", None)

        self._make_action("about", self._show_about)
        self._make_action("quit", lambda *_: self.quit())
        self._make_action("refresh", self._refresh)
        self._make_action("preferences", self._show_preferences)

        self.set_accels_for_action("app.quit", ["<Control>q"])
        self.set_accels_for_action("app.refresh", ["<Control>r"])
        self.set_accels_for_action("app.preferences", ["<Control>comma"])
        self.set_accels_for_action("win.show-help-overlay", ["<Control>question"])

    def _make_action(self, name: str, cb) -> Gio.SimpleAction:
        action = Gio.SimpleAction.new(name, None)
        action.connect("activate", cb)
        self.add_action(action)
        return action

    # ── lifecycle ─────────────────────────────────────────────────
    def do_startup(self):
        Adw.Application.do_startup(self)
        # First run on a machine with a pulse database: adopt it before
        # the store creates a fresh one (no-op in every other case).
        try:
            self._adoption = migrate.adopt()
        except Exception:
            log.exception("pulse database adoption failed; starting fresh")
            self._adoption = None
        resources.db_path().parent.mkdir(parents=True, exist_ok=True)
        self.store = Store(str(resources.db_path()))
        self.store.migrate()
        self.catalog = Catalog.load()
        self.recorder = Recorder(self.store, self.catalog, self.record_bus)

    def do_shutdown(self):
        if self.store is not None:
            self.store.close()
        Adw.Application.do_shutdown(self)

    def do_activate(self):
        win = self.props.active_window
        if win is None:
            win = VitalsWindow(application=self)
            if self._adoption and self._adoption.get("adopted"):
                win.show_toast(
                    f"Imported {self._adoption['records']:,} records from "
                    "Pulse — the retiring apps no longer feed this data")
                self._adoption = None
        win.present()

    # ── actions ───────────────────────────────────────────────────
    def _refresh(self, *_):
        win = self.props.active_window
        if win is not None:
            win.refresh()

    def _show_preferences(self, *_):
        from vitals.preferences import VitalsPreferences
        win = self.props.active_window
        if win is not None:
            VitalsPreferences(self.settings).present(win)

    def _show_about(self, *_):
        about = Adw.AboutDialog(
            application_name=APP_NAME,
            application_icon=APP_ID,
            version=VERSION,
            license_type=Gtk.License.GPL_3_0,
            developer_name="Rob Daniel",
            comments="Health tracking for watches, sensors and manual logs.",
            website="https://codeberg.org/robland/vitals",
            issue_url="https://codeberg.org/robland/vitals/issues",
        )
        about.add_acknowledgement_section(
            "Generated by", ("Claude (Anthropic)\nhttps://claude.com",))
        about.present(self.props.active_window)
