"""Vitals — Adw.Application subclass."""

from __future__ import annotations

import logging

from gi.repository import Adw, Gio, GLib, Gtk

from vitals.const import APP_ID, APP_NAME, VERSION
from vitals.pulse_client import PulseClient
from vitals.window import VitalsWindow

log = logging.getLogger(__name__)


class VitalsApplication(Adw.Application):
    def __init__(self):
        super().__init__(application_id=APP_ID,
                         flags=Gio.ApplicationFlags.DEFAULT_FLAGS)
        self._settings = Gio.Settings.new(APP_ID)
        self._client = PulseClient()

        # Registered so --help lists it and Gio accepts it; the actual
        # level is read from sys.argv by configure_logging().
        self.add_main_option(
            "debug", ord("d"), GLib.OptionFlags.NONE, GLib.OptionArg.NONE,
            "Enable debug logging", None)

        self._make_action("about", self._show_about)
        self._make_action("quit", lambda *_: self.quit())
        self._make_action("refresh", self._refresh)

        self.set_accels_for_action("app.quit", ["<Control>q"])
        self.set_accels_for_action("app.refresh", ["<Control>r"])
        self.set_accels_for_action("win.show-help-overlay", ["<Control>question"])

    def _make_action(self, name: str, cb) -> Gio.SimpleAction:
        action = Gio.SimpleAction.new(name, None)
        action.connect("activate", cb)
        self.add_action(action)
        return action

    def do_activate(self):
        win = self.props.active_window
        if win is None:
            win = VitalsWindow(application=self, settings=self._settings,
                               client=self._client)
        win.present()

    def _refresh(self, *_):
        win = self.props.active_window
        if win is not None:
            win.refresh()

    def _show_about(self, *_):
        about = Adw.AboutDialog(
            application_name=APP_NAME,
            application_icon=APP_ID,
            version=VERSION,
            license_type=Gtk.License.GPL_3_0,
            developer_name="Rob Daniel",
            comments="Health dashboard for the Pulse hub.",
            website="https://codeberg.org/robland/vitals",
            issue_url="https://codeberg.org/robland/vitals/issues",
        )
        about.add_acknowledgement_section(
            "Generated by", ("Claude (Anthropic)\nhttps://claude.com",))
        about.present(self.props.active_window)
