"""Locate the bundled health-data files (catalog, SQL migrations).

The core must run both from an installed tree (files under
``PKGDATADIR``) and from a source checkout (files under ``data/schema/``
at the repo root). This module resolves a single *data root* that
contains ``record-types.yaml`` and ``sql/`` and exposes loaders on top
of it. The lookup order is:

  1. ``$VITALS_DATA_DIR``                      (explicit override / tests)
  2. ``const.PKGDATADIR``                      (installed build)
  3. ``<repo>/data/schema`` discovered from ``__file__``  (source checkout)
"""

from __future__ import annotations

import os
from pathlib import Path

try:  # const.py is generated by Meson from const.py.in at build time.
    from vitals import const  # type: ignore

    _PKGDATADIR = getattr(const, "PKGDATADIR", None)
except Exception:  # pragma: no cover - exercised only in installed builds
    _PKGDATADIR = None


def _is_data_root(path: Path) -> bool:
    return (path / "record-types.yaml").is_file()


def _discover_source_root() -> Path | None:
    # src/vitals/core/resources.py -> repo root holds data/schema/.
    here = Path(__file__).resolve()
    for parent in here.parents:
        candidate = parent / "data" / "schema"
        if _is_data_root(candidate):
            return candidate
    return None


def data_root() -> Path:
    """Return the directory holding the bundled data files."""
    candidates: list[Path] = []
    env = os.environ.get("VITALS_DATA_DIR")
    if env:
        candidates.append(Path(env))
    if _PKGDATADIR:
        candidates.append(Path(_PKGDATADIR))
    source_root = _discover_source_root()
    if source_root:
        candidates.append(source_root)

    for path in candidates:
        if _is_data_root(path):
            return path
    raise FileNotFoundError(
        "could not locate vitals data files (record-types.yaml); "
        "set VITALS_DATA_DIR or install the package"
    )


def catalog_path() -> Path:
    return data_root() / "record-types.yaml"


def migration_files() -> list[Path]:
    """Return migration SQL files sorted by their numeric prefix."""
    sql_dir = data_root() / "sql"
    return sorted(sql_dir.glob("[0-9]*.sql"))


def user_data_dir() -> Path:
    """Per-user writable data directory for the health database."""
    override = os.environ.get("VITALS_USER_DATA_DIR")
    if override:
        return Path(override)
    xdg = os.environ.get("XDG_DATA_HOME") or os.path.expanduser("~/.local/share")
    return Path(xdg) / "vitals"


def db_path() -> Path:
    return user_data_dir() / "health.db"
